<?php
$apiKey = "rzp_test_wNMdT8Wr27usMV";
?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<!---
<form action="" method="POST">
<script>
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Child Development"
    data-description="Payment Now!"
    data-image="https://www.motocms.com/blog/wp-content/uploads/2017/11/1040-563-3.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.phone number="<?php echo $_POST['phone number'];?>"
    data-theme.color="#F37254"
</script>
--->

<form action="https://www.example.com/payment/success/" method="POST">
<script>
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount']* 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Child Development NGO "
    data-description="Trains & Development!"
    data-image="https://www.motocms.com/blog/wp-content/uploads/2017/11/1040-563-3.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.phone number="<?php echo $_POST['phone number'];?>"
    data-theme.color="#F37254"
</script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>






















